version: "3.8"

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: tien2704200/devops:latest
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
